### ISSUE TITLE
Consider adding META-INF/services/io.r2dbc.spi.ConnectionFactoryProvider

### ISSUE THREAD

**Issue by mp911de** [oracle/oracle-r2dbc#10]
Right now, the ServiceLoader information is only activated when using the module path. It would be nice to not be required to use Java Modules to use the driver (i.e being able to use classpath mode).

**Comment by Michael-A-McMahon** [comment]
Thanks, @mp911de.
It should be the case that non-modular code bases are supported. I'll look into why this isn't working as intended.

FYI: A /services/io.r2dbc.spi.ConnectionFactoryProvider file is present: https://github.com/oracle/oracle-r2dbc/blob/main/src/main/resources/META-INF/services/io.r2dbc.spi.ConnectionFactoryProvider
But I'm not sure sure why the ServiceLoader isn't recognizing it.

**Comment by Michael-A-McMahon** [comment]
I now see that our services directory is no longer included in our jars when we build with maven. Might be related to recent changes in pom.xml? I'll come back to this tomorrow.
