### ISSUE TITLE
Maven Repository v1.1.0

### ISSUE THREAD

**Issue by vladimirfx** [oracle/oracle-r2dbc#109]
No artifact in Maven Central in 12 days from release. Sims something gets wrong.

**Comment by Michael-A-McMahon** [comment]
I'm investigating this. A 12 day delay is really too much.

We had created a request to publish artifacts a week ago, but it is still pending. I suspect that the US holidays may have delayed the process. Now that they are over, we should have this done today.

If you need a release that is compatible with the 1.0.0 SPI, Oracle R2DBC 1.0.0 is available now.

The ShedLock project looks interesting, BTW :)

**Comment by vladimirfx** [comment]
Oh, thank you. I've misunderstood description in readme. Will fix my PR in r2dbc-migrate.

**Comment by Michael-A-McMahon** [comment]
Glad I could help. Let's leave this issue open so that others can find it. I suspect you're not the only one wondering where the artifacts are.

**Comment by Michael-A-McMahon** [comment]
1.1.0 has arrived!!!
https://repo1.maven.org/maven2/com/oracle/database/r2dbc/oracle-r2dbc/1.1.0/
