### ISSUE TITLE
Error occurs if ConnectionFactoryOptions.PROTOCOL option is an empty string

### ISSUE THREAD

**Issue by nakamura-to** [oracle/oracle-r2dbc#111]
Hi. The error occurs in v1.1.0 but not in v1.0.0.

I guess we need to check if the `protocol` is empty here.
https://github.com/oracle/oracle-r2dbc/blob/1.1.0/src/main/java/oracle/r2dbc/impl/OracleReactiveJdbcAdapter.java#L407

In some cases,　r2dbc-pool sets an empty string to the `ConnectionFactoryOptions.PROTOCOL` option.
https://github.com/r2dbc/r2dbc-pool/blob/v1.0.0.RELEASE/src/main/java/io/r2dbc/pool/PoolingConnectionFactoryProvider.java#L180

**Comment by Michael-A-McMahon** [comment]
Thanks for finding this. The driver should be treating an empty string as if the protocol was not set.
I'll have a fix for this soon.
