### ISSUE TITLE
Operator has been terminated issue with RowsFetchSpec and Spring DatabaseClient

### ISSUE THREAD

**Issue by sephiroth-j** [oracle/oracle-r2dbc#133]
When a mapping function via `map` is used on a `GenericExecuteSpec`, the `onErrorDropped` hook is triggered twice and the following error is logged. This does not happen when `fetch` is used with its default row mapper that maps the result to a `Map<String,Object>`. The query is successfully executed in both cases.

**Error**
```
2023-09-19T11:00:49.267+02:00 ERROR 4268 --- [onPool-worker-1] reactor.core.publisher.Operators         : Operator called default onErrorDropped

reactor.core.Exceptions$StaticThrowable: Operator has been terminated

2023-09-19T11:00:49.271+02:00 ERROR 4268 --- [onPool-worker-1] reactor.core.publisher.Operators         : Operator called default onErrorDropped

reactor.core.Exceptions$StaticThrowable: Operator has been terminated
```

**Example**
```java
@DataR2dbcTest(properties =
{
	"spring.r2dbc.url=r2dbc:oracle://testdb",
	"spring.r2dbc.username=sa",
	"spring.r2dbc.password=sa",
})
class DatabaseClientTest
{
	@Autowired
	private DatabaseClient dbClient;

	@Test
	void testMethod()
	{
		dbClient.sql("select '1234' value from dual")
				.map(readable -> readable.get(0, String.class)).first()// onErrorDropped: Operator has been terminated
//				.fetch().one().map(row -> row.get("value")).cast(String.class)// no onErrorDropped
				.as(StepVerifier::create)
				.expectNext("1234")
				.verifyComplete();
	}
}
```
[spring-oracle-r2dbc-issue.zip](https://github.com/oracle/oracle-r2dbc/files/12657964/spring-oracle-r2dbc-issue.zip)

**Comment by sephiroth-j** [comment]
Hm, it seems that the mapping function is not the problem. It's `one()` vs `first()`  that makes the difference. `first()` causes the error while `one()` does not.

**Comment by Michael-A-McMahon** [comment]
Hi, @sephiroth-j. Thank you for reporting this.

I think I've got a fix: #134 

In a nutshell: Oracle R2DBC will handle resource clean up the way Project Reactor intends it to: Flux.usingWhen(...)

**Comment by sephiroth-j** [comment]
Hey, thanks for the quick solution. Until the release with the fix is available, I can use `one()` in combination with a "limit 1" clause as a workaround ... which probably makes more sense anyway, since I'm only interested in the first row anyway.

**Comment by sephiroth-j** [comment]
Hi @Michael-A-McMahon, can you give an estimated date for the release of this fix?

**Comment by Michael-A-McMahon** [comment]
Hi @sephiroth-j, I'll check with my team about a new release. I think we are due for one. I can't estimate a date right now, but I'll update this thread once I know more.

**Comment by Michael-A-McMahon** [comment]
Going to get a few more changes in this week, and then get our release process started. Next release could happen by the end of next week, but there's no guarantee.
