### ISSUE TITLE
How to configure SECURITY=(SSL_SERVER_CERT_DN) Option in R2dbc connection String with Descriptor

### ISSUE THREAD

**Issue by Krithika-Madhavan** [oracle/oracle-r2dbc#135]
Hi Team, 

We are trying to use CERTS on Connection string as like JDBC , but it seems not working in R2dbc. Is there any way to do this in r2dbc?

**Comment by Michael-A-McMahon** [comment]
Hi, @Krithika-Madhavan. Thank you for your question.

Oracle R2DBC can be configured to use a "(DESCRIPTION=...(SECURITY=..(SSL_SERVER_CERT_DN=...)" style URL:
https://github.com/oracle/oracle-r2dbc#configuring-an-oracle-net-descriptor

Oracle R2DBC also has an Option which can configure the certificate DN:
https://github.com/oracle/oracle-r2dbc/blob/8e923ae761ad43630c0dfc6b6dea419d9b18733d/src/main/java/oracle/r2dbc/OracleR2dbcOptions.java#L141

Hope this helps.

**Comment by Krithika-Madhavan** [comment]
Thanks @Michael-A-McMahon
