### ISSUE TITLE
CONNECTION_PROPERTY_PROXY_CLIENT_NAME not present in OracleR2dbcOptions

### ISSUE THREAD

**Issue by deb538** [oracle/oracle-r2dbc#154]
OracleConnection class (https://docs.oracle.com/en/database/oracle/oracle-database/19/jajdb/oracle/jdbc/OracleConnection.html) has a field CONNECTION_PROPERTY_PROXY_CLIENT_NAME
![image](https://github.com/user-attachments/assets/8bc3e71a-69b1-4555-8e52-a121acf3aa50)

We use this field in our application.

We are moving to R2DBC. Extended options supported by Oracle R2DBC in https://github.com/oracle/oracle-r2dbc/blob/main/src/main/java/oracle/r2dbc/OracleR2dbcOptions.java  does not have field CONNECTION_PROPERTY_PROXY_CLIENT_NAME. 
![image](https://github.com/user-attachments/assets/e31fcf8f-c71c-4ab2-97a4-769497a95cca)

Please review and let me if there is any other way to pass proxy client name or it needs a fix.

**Comment by Michael-A-McMahon** [comment]
We should add this into `OracleR2dbcOptions`. Let's leave this issue open as a reminder to do that.

Working with the current release of Oracle R2DBC, it should be possible to configure this as a system property "-Doracle.jdbc.proxyClientName=...", or you can configure this in a [connection properties file](https://docs.oracle.com/en/database/oracle/oracle-database/23/jajdb/oracle/jdbc/OracleConnection.html#CONNECTION_PROPERTY_CONFIG_FILE).

**Comment by deb538** [comment]
-Doracle.jdbc.proxyClientName=..." works. Thanks for your quick response. 
May I know when the code fix can be available.

**Comment by Michael-A-McMahon** [comment]
Sorry, but I can't commit to any timeline right now.
