### ISSUE TITLE
How does a behavior of fetching all records from a table work?

### ISSUE THREAD

**Issue by tfariassantanna** [oracle/oracle-r2dbc#156]
So, I'm opening this item, but as a question rather than a problem.

I wanted to understand how a search for all records in a table works under the hood.

For example, is a cursor opened? I see that it's a very common practice in reactive drivers to use cursors to return the elements of a table and thus, as the "Results" are emitted, we would have a Streamming flow.

Am I right with this view or not?

Could someone help me understand this point?

Thank you very much in advance!

**Comment by Michael-A-McMahon** [comment]
Your intuition is correct. When Oracle R2DBC sends a SELECT query to Oracle Database, the database returns the ID of a cursor. Oracle R2DBC then requests row data from the cursor in batches. The batch size is configured by `Statement.fetchSize(int)`. 
Say you've configure fetchSize as 100, and your SELECT query returns 1000 rows: When the SELECT query is first sent to the database, the database returns the first 100 rows. Your `Subscriber` receives the row data in response to calling `Subscription.request(long)`. Each call to `request` increases a cumulative total of requested rows. When the total exceeds 100, a request for the next 100 rows is sent to the database. This repeats until all 1000 rows have been requested and emitted to the Subscriber.

Configuring fetch size is a balance between memory usage and latency. A lower fetch size will use less memory as there is less row data to hold in a buffer. And a higher fetch size will reduce latency as there are less request/response round trips going over the network between Oracle R2DBC and Oracle Database.
```
Low Fetch Size  = Lower Memory Usage  + Higher Latency
High Fetch Size = Higher Memory Usage + Lower Latency
```
_In the current release of Oracle R2DBC, you almost always want to configure a fetch size._ The default is a ridiculously small value of 10. In the example above, that would mean 100 network round trips are needed to fetch 1000 rows. The network latency is going to be a huge cost, unless your network connection to the database is incredibly fast.
I recommend increasing the fetch size to match your memory capacity. We can try to calculate a fetchSize by considering the number of concurrent database connections, the maximum size of each row, and the amount of memory available: 
```
fetchSize = available-memory / (max-connections * max-row-size)
```
Let's say each row uses upto 1kb of memory, our connection pool is sized at 10, and our system has 100MB of memory to spare for Oracle R2DBC:
```
fetchSize = 100M / (10 * 1K) = 10000
```
That's theoretical number, only possible in a vacuum where no memory is being allocated for anything else besides row data. So we can subtract some amount from `available-memory` to account for other usages. 
We could also think about a per-connection and per-row overhead memory cost, and factor these into the equation as well. An additional thing to consider is if rows are being fetched from multiple statements/cursors of a single connection; In my formula, I've assumed that each connection has just one statement/cursor open at time.
How much you want to put into this calculation depends how close to the edge of the `OutOfMemoryError` cliff you want to go. I think for most users, "good enough" performance can be obtained while staying a safe distance away from this cliff.


Final thing I'll note is that the next release of Oracle R2DBC (coming soon) will update the Oracle JDBC dependency from 21 to 23. The 23 release of Oracle JDBC will automatically tune the fetch size when a user doesn't configure one. So the default behavior won't be a fixed 10 row fetch size, and it might spare a lot of users from having to work out calculations like the one above.

**Comment by santannaf** [comment]
Perfect, thank you very much for the clarification!

**Comment by Michael-A-McMahon** [comment]
Glad I could help :)
