### ISSUE TITLE
Transaction isolation

### ISSUE THREAD

**Issue by spencercw** [oracle/oracle-r2dbc#44]
Hi, just wondering where support for transaction isolation levels other than READ COMMITED might be on the roadmap? Thanks.

**Comment by Michael-A-McMahon** [comment]
Hi, @spencercw. Other than READ COMMITTED, SERIALIZABLE would be the only isolation level that Oracle Database supports.

We've looked at how Oracle JDBC implements java.sql.Connection.setIsolationLevel(int) and noticed it would disable the client-side ResultSet cache when SERIALIZABLE was set. I think the idea is that returning a cached ResultSet could violate the guarantee of no phantom reads in a SERIALIZABLE transaction, so the JDBC driver is implemented to disable this once a SERIALIZABLE transaction starts.

For Oracle R2DBC, we'd want to replicate the behavior of JDBC's setTransaction with a non-blocking implementation. It's trivial enough for Oracle R2DBC to implement a non-blocking execution of "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE". But Oracle JDBC doesn't offer an API to disable the cache, so Oracle R2DBC can't replicate that behavior.

I can discuss with the Oracle JDBC Team about adding a method to oracle.jdbc.OracleConnection that disables the ResultSet cache. If the team to agrees to add this method, then Oracle R2DBC can offer a proper implementation that replicates the behavior of JDBC.

In the mean time, we could support an R2DBC Option that configures the oracle.jdbc.enableQueryResultCache connection property. This Option could be set to "false" to disable the cache entirely. Oracle R2DBC can document that programmers who use the SERIALIZABLE isolation level should also disable the cache.

I'd be interested to hear feedback on this. As a stop-gap solution, is it acceptable to have an Option that would disable the cache?

**Comment by spencercw** [comment]
Thanks for the detailed response. That's interesting, I didn't know that Oracle doesn't support REPEATABLE READ. SERIALIZABLE is what I was after anyway.

I think that sounds like a reasonable workaround until a proper solution can be implemented. Certainly it seems preferable to SERIALIZABLE being completely unavailable in the R2DBC driver.
