### ISSUE TITLE
Connection issue with R2DBC, but not jdbc

### ISSUE THREAD

**Issue by Stefanqn** [oracle/oracle-r2dbc#62]
To follow up my [stackoverflow question](https://stackoverflow.com/questions/70832192/how-is-oracles-r2dbc-driver-different-from-ojdbc-connection-wise?noredirect=1#comment125231228_70832192), where jdbc connects, but r2dbc doesn't.

How can I print the ConnectionFactoryOption that are actually used for the jdbc and r2dbc connection?

**Comment by Michael-A-McMahon** [comment]
We can print log messages by enabling Oracle JDBC's diagnostic logging. You'll need to have the ojdbc11_g jar on the classpath to use logging. More details about configuring logging can be found in the Developer's Guide:
https://docs.oracle.com/en/database/oracle/oracle-database/21/jjdbc/JDBC-diagnosability.html#GUID-4925EAAE-580E-4E29-9B9A-84143C01A6DC

In the face of hangs, I find it useful to dump the JVM threads. This will let us see where our threads are hanging. The jstack command, or CRTL+\ will produce a thread dump. 

Also, just in case you haven't already, please be sure to review the Connection Creation section here:
https://github.com/oracle/oracle-r2dbc#connection-creation
This section explains the options and URL components that Oracle R2DBC supports. It also explains how Oracle R2DBC uses these options and URL components to configure the JDBC connection.

**Comment by Stefanqn** [comment]
After we couldn't figure out what prevented r2dbc from connecting to the oracle DB, we basically switched back to jdbc due to time constraints. I'm sorry for not being able to dig deeper into what happened. I'm closing the issue for that reason.
