### ISSUE TITLE
R2DBC integration with Mutiny example

### ISSUE THREAD

**Issue by LazaroR94** [oracle/oracle-r2dbc#65]
I am new to both reactive-programming and R2DBC. I have recently come to know about a reactive oracle API (R2DBC) and wanted to see how I can integrate this inside my Quarkus/Kotlin project using Mutiny. I've seen the Mutiny example on https://r2dbc.io but wanted to know how I can convert this to, let's say, an entity that maps to a table? Essentially, I want to only perform database inserts based on the given entities but I see that R2DBC's example is just a simple native query. How can I accomplish this? I am currently using Hibernate ORM with Panache.

I will post here a sample snippet of my current code using only Mutiny:

    fun save(entity: SomeDatabaseEntity): Uni<Void> =
        Uni.createFrom().voidItem().invoke { -> someDatabaseRepository.persistEntity(entity) }

Is there a similar way that I can achieve the above with R2DBC? Any suggestions/tips are greatly appreciated, thanks!

**Comment by Michael-A-McMahon** [comment]
Just thought that I should also mention Spring Data R2DBC. The Spring project has also done great work to provide a reactive ORM:
https://spring.io/projects/spring-data-r2dbc

Spring Data R2DBC exposes the Flux and Mono types of Project Reactor. However, these types implement the org.reactivestreams.Publisher interface, so it should be possible to adapt them into Mutiny types.
https://smallrye.io/smallrye-mutiny/guides/converters

**Comment by Michael-A-McMahon** [comment]
@LazaroR94 I hope I was able to help. I'm going to close this issue now, but please let me know if there's more to discuss.

**Comment by Swe77** [comment]
I think the response is using this dependency:

<dependency>
    <groupId>io.smallrye.reactive</groupId>
    <artifactId>mutiny-reactor</artifactId>
    <version>1.6.0</version>
</dependency>

More details can be found in this link:
https://smallrye.io/smallrye-mutiny/1.6.0/guides/converters/
