### ISSUE TITLE
Timeline: Maven Repository v1.0.0 jar

### ISSUE THREAD

**Issue by rmalired** [oracle/oracle-r2dbc#78]
Any timeline that oracle-r2dbc-1.0.0 will be available on maven central repository ?

**Comment by Michael-A-McMahon** [comment]
Typically, it takes a day or two before jars make their way on to Maven.

I just checked in on this, and it seems there is some testing and verification going on at the moment. Hopefully it'll all be ready soon.

**Comment by Michael-A-McMahon** [comment]
Oracle R2DBC 1.0.0 has now arrived!
https://repo1.maven.org/maven2/com/oracle/database/r2dbc/oracle-r2dbc/1.0.0/

I'm very sorry about the delay. Going forward, we'll do a better job when it comes to getting releases on to Maven.

**Comment by sgtcortez** [comment]
Thank you @Michael-A-McMahon
