### ISSUE TITLE
Question. Could someone tell me where can I find the project com.oracle.database.jdbc:ojdbc8 ?

### ISSUE THREAD

**Issue by cvgaviao** [oracle/oracle-r2dbc#87]
I'm using the following artifact and I would like to open an issue related to it:
<groupId>com.oracle.database.jdbc</groupId>
<artifactId>ojdbc8</artifactId>
<version>21.4.0.0.1</version>

**Comment by Michael-A-McMahon** [comment]
This is the Oracle JDBC Driver. It is available on maven:
https://www.oracle.com/database/technologies/maven-central-guide.html

Oracle JDBC is (sadly) not open source, so the project is not hosted on GitHub. Is this what you were looking for?

**Comment by Kuassim** [comment]
@cvgaviao I am guessing you don't have an Oracle SUpport contract for filing a service request against JDBC; in that case you can submit the issue on StackOverflow. We monitor it regularly. However, if the issue turns out to be a bug, you would need a support contract to get the fix.

**Comment by cvgaviao** [comment]
@Kuassim and @Michael-A-McMahon, thanks for the information. I don't have the Oracle support.

But anyway, I'm going to write here what I've found. perhaps you can forward to the responsible team.

While I was trying to create a native-image (graalvm) for a project that uses this driver, I've received a warning of a conflicted native-image configuration on the META-INF dir.

The issue is due the fact that ojdbc8.jar is not following the recommended directory naming from NativeImage doc.  see below:

```
To avoid a situation when constituent parts of a project are built with overlapping configurations, we recommended you use subdirectories within META-INF/native-image: a JAR file built from multiple maven projects cannot suffer from overlapping native-image configurations. For example:

foo.jar has its configurations in META-INF/native-image/foo_groupID/foo_artifactID
bar.jar has its configurations in META-INF/native-image/bar_groupID/bar_artifactID

```

**Comment by Michael-A-McMahon** [comment]
Thank you for bringing this to our attention, @cvgaviao. We've passed the info along to a GraalVM expert on the JDBC team.
