### ISSUE TITLE
IllegalStateException: One or more parameters are not set on reusing named parameter multiple times

### ISSUE THREAD

**Issue by mp911de** [oracle/oracle-r2dbc#9]
It seems that using a named parameter multiple times isn't working properly. 

Consider the following statement:

```sql
SELECT id, name, manual FROM legoset WHERE name = :P0_name or name = :P0_name
```

Trying to run the statement with:

```java
Mono.from(connectionFactory.create())
		.flatMapMany(it -> {

	return it.createStatement("SELECT id, name, manual FROM legoset WHERE name = :P0_name or name = :P0_name")
		.bind("P0_name", "unknown")
		.execute();
	}).flatMap(it -> it.map((row, rowMetadata) -> row.get(0))).blockLast();
```

fails with:

```
java.lang.IllegalStateException: One or more parameters are not set

	at oracle.r2dbc.impl.OracleStatementImpl.requireAllParametersSet(OracleStatementImpl.java:790)
	at oracle.r2dbc.impl.OracleStatementImpl.add(OracleStatementImpl.java:341)
	at oracle.r2dbc.impl.OracleStatementImpl.execute(OracleStatementImpl.java:458)
```

Running the statement as `SELECT id, name, manual FROM legoset WHERE name = :P0_name` works fine.

**Comment by Michael-A-McMahon** [comment]
@mp911de: Thanks for finding this. 
I'll see about fixing this, such that setting a bind value by name will set a value for **all** parameters that match the specified name; The current implementation just sets a value for the first occurrence of a parameter with a matching name.
